#!/bin/sh

export ADDITIONAL_FILES_BASE_URL="http://10.0.0.1/tcc/"

# linic - I changed the --enable-kernel=6.1.2 to 4.4.0
export ENABLE_KERNEL="4.4.0"
# linic - I changed the -march=i486 for -march=i686
export MARCH="i686"
export MTUNE="i686"

export AUTOCONF_PACKAGE_NAME="autoconf-2.72"
export AUTOMAKE_PACKAGE_NAME="automake-1.17"
export BASH_PACKAGE_NAME="bash-5.2.37"
export BC_PACKAGE_NAME="bc-7.0.3"
export BINUTILS_PACKAGE_NAME="binutils-2.43.1"
export BISON_PACKAGE_NAME="bison-3.8.2"
export BUSYBOX_PACKAGE_NAME="busybox-1.36.1"
export BZIP2_PACKAGE_NAME="bzip2-1.0.8"
export COREUTILS_PACKAGE_NAME="coreutils-9.5"
export DIFFUTILS_PACKAGE_NAME="diffutils-3.10"
export E2FSPROGS_PACKAGE_NAME="e2fsprogs-1.47.1"
export EXPAT_PACKAGE_NAME="expat-2.6.4"
export FILE_PACKAGE_NAME="file-5.46"
export FINDUTILS_PACKAGE_NAME="findutils-4.10.0"
export FLEX_PACKAGE_NAME="flex-2.6.4"
export GAWK_PACKAGE_NAME="gawk-5.3.1"
export GCC_PACKAGE_NAME="gcc-14.2.0"
export GETTEXT_PACKAGE_NAME="gettext-0.22.5"
export GLIBC_PACKAGE_NAME="glibc-2.40"
export GMP_PACKAGE_NAME="gmp-6.3.0"
export GPERF_PACKAGE_NAME="gperf-3.1"
export GREP_PACKAGE_NAME="grep-3.11"
export GROFF_PACKAGE_NAME="groff-1.23.0"
export GZIP_PACKAGE_NAME="gzip-1.13"
export INTLTOOL_PACKAGE_NAME="intltool-0.51.0"
export ISL_PACKAGE_NAME="isl-0.24"
export LIBTOOL_PACKAGE_NAME="libtool-2.5.4"
export LIBXCRYPT_PACKAGE_NAME="libxcrypt-4.4.36"
export LINUX_PACKAGE_NAME="linux-cip-4.4.302-cip97"
export M4_PACKAGE_NAME="m4-1.4.19"
export MAKE_PACKAGE_NAME="make-4.4.1"
export MPC_PACKAGE_NAME="mpc-1.3.1"
export MPFR_PACKAGE_NAME="mpfr-4.2.1"
export NCURSES_PACKAGE_NAME="ncurses-6.5"
export PATCH_PACKAGE_NAME="patch-2.7.6"
export PERL_PACKAGE_NAME="perl-5.32.0"
export PKG_CONFIG_PACKAGE_NAME="pkg-config-0.29.2"
export PYTHON_PACKAGE_NAME="Python-3.13.0"
export READLINE_PACKAGE_NAME="readline-8.2.13"
export SED_PACKAGE_NAME="sed-4.9"
export TAR_PACKAGE_NAME="tar-1.35"
export TEXINFO_PACKAGE_NAME="texinfo-7.1.1"
export UTIL_LINUX_PACKAGE_NAME="util-linux-2.40.2"
export XML_PARSER_PACKAGE_NAME="XML-Parser-2.47"
export XZ_PACKAGE_NAME="xz-5.6.3"
export ZLIB_PACKAGE_NAME="zlib-1.3.1"
export ZSTD_PACKAGE_NAME="zstd-1.5.6"
